#' 执行微生物群落样本级富集分析 (Sample-Level Enrichment Analysis)
#'
#' 该函数接受 phyloseq 对象，针对特定的目标微生物，分析样本元数据特征是否在
#' 该微生物高丰度或低丰度的样本中富集。
#'
#' @param ps A `phyloseq` object.
#' @param taxon_target A character string. The target taxon name (e.g., "Escherichia").
#' @param taxon_rank A character string. The rank of the target taxon (e.g., "Genus").
#' @param sample_feat A character string. The metadata column name to group samples (e.g., "Group").
#' @param min_size Integer. Minimum size of a feature set. Default is 5.
#' @param max_size Integer. Maximum size of a feature set. Default is 500.
#' @param descreasing Logical. Whether to sort in decreasing order. Default is TRUE.
#'
#' @return A `data.frame` (tbl_df) containing the GSEA results.
#' Columns include: pathway, pval, padj, NES, size, leadingEdge.
#'
#' @importFrom phyloseq tax_table otu_table sample_names rank_names sample_data taxa_are_rows
#' @importFrom fgsea fgsea
#' @importFrom dplyr arrange desc select
#' @importFrom tibble as_tibble
#' @importFrom rlang .data
#'
#' @examples
#' \dontrun{
#' # Suppose there is a ps object.
#' res <- run_microbiome_gsea(
#'     ps = ps_test_data,
#'     taxon_target = "Genus1",
#'     taxon_rank = "Genus",
#'     sample_feat = c("Group", "Source")
#' )
#' print(res)
#' }
#' @export
run_microbiome_gsea <- function(ps, taxon_target, taxon_rank, sample_feat,
                                min_size = 5, max_size = 500,
                                descreasing = TRUE) {

  # 1. 获取排序后的丰度向量 (Stats)
  # 这一步包含了 Z-score 标准化
  message(paste("Calculating ranked abundance for:", taxon_target, "..."))
  sample_ranks <- get_sorted_abundance_vector(ps, taxon_target, taxon_rank, decreasing = descreasing)

  # 2. 获取样本特征集合 (Sets)
  message(paste("Generating sample sets for feature:", sample_feat, "..."))
  sample_sets <- get_sample_feature_sets(ps, sample_feat)

  # 检查是否有足够的集合进行分析
  if (length(sample_sets) == 0) {
    stop("No valid sample sets generated. Check your metadata column or min_size.")
  }

  # 3. 运行 fgsea
  message("Running GSEA analysis...")

  # 设置随机种子以保证结果可重复
  set.seed(123)

  gsea_res <- fgsea::fgsea(
    pathways = sample_sets,
    stats    = sample_ranks,
    minSize  = min_size,
    maxSize  = max_size
  )

  # 4. 结果整理
  # 转换为 tibble 并按 NES (Normalized Enrichment Score) 绝对值或数值排序
  # 这里按 NES 降序排列 (正富集在前，负富集在后)
  gsea_res <- gsea_res %>%
      dplyr::arrange(dplyr::desc(.data$NES)) %>%
      tibble::as_tibble()

  # 5. 添加属性以便后续绘图
  attr(gsea_res, "sampleSets") <- sample_sets
  attr(gsea_res, "sampleRanks") <- sample_ranks

  return(gsea_res)
}


#' Plot GSEA Enrichment Score
#'
#' This function plots the GSEA enrichment score curve for a specific sample set (pathway)
#' using the results from `run_microbiome_gsea`.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should be a
#'   data frame with "sampleSets" and "sampleRanks" attributes.
#' @param set_name A character string. The name of the set (pathway) to plot.
#'
#' @return A ggplot object (generated by `fgsea::plotEnrichment`).
#'
#' @importFrom fgsea plotEnrichment
#' @importFrom ggplot2 labs
#' @export
#' @examples
#' \dontrun{
#' gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' gsea_plot(gsea_res, "Group_Treat")
#' }
gsea_plot = function(gsea_res, set_name){
  sample_sets = attr(gsea_res, "sampleSets")
  sample_ranks = attr(gsea_res, "sampleRanks")

  p_val <- gsea_res$padj[gsea_res$pathway == set_name]
  p_val_fmt <- format(p_val, scientific = TRUE, digits = 3)
  NES <- format(gsea_res[["NES"]][gsea_res$pathway == set_name], digits = 3)

  lab = paste0(set_name, " (p.adj = ", p_val_fmt, ", NES = ", NES, ")")

  fgsea::plotEnrichment(sample_sets[[set_name]], sample_ranks) +
    ggplot2::labs(subtitle = lab)
}

#' Plot all GSEA enrichment score curves
#'
#' This function generates and arranges GSEA enrichment plots for all significant (or specified)
#' pathways from the GSEA results.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should contain the GSEA results
#'   and attributes "sampleSets" and "sampleRanks".
#' @param filter A logical value. If `TRUE` (default), filters the results to include only
#'   pathways with adjusted p-value < 0.05.
#' @param ... Additional arguments passed to `cowplot::plot_grid` (e.g., `ncol`, `labels`).
#'
#' @return A ggplot object (combined plot generated by `cowplot::plot_grid`).
#'
#' @importFrom dplyr filter
#' @importFrom cowplot plot_grid
#' @importFrom rlang .data
#' @export
#' @examples
#' \dontrun{
#' # gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' # gsea_plot_all(gsea_res)
#' }
gsea_plot_all = function(gsea_res, filter = TRUE, ...){
  if (filter){
    gsea_res = dplyr::filter(gsea_res, .data[['padj']] < 0.05)
  }
  sets = gsea_res$pathway
  if (length(sets) < 1){
    stop("At least one set needed.")
  }
  gglist = lapply(sets, gsea_plot, gsea_res = gsea_res)
  cowplot::plot_grid(plotlist = gglist, ...)
}
