
#' Plot GSEA Enrichment Score
#'
#' This function plots the GSEA enrichment score curve for a specific sample set (pathway)
#' using the results from `run_microbiome_gsea`.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should be a
#'   data frame with "sampleSets" and "sampleRanks" attributes.
#' @param set_names A character vector The name of the sets (pathway) to plot.
#' @param show_table A logical value. If `TRUE`, shows a table of p-values and NES alongside the plot.
#'
#' @return A ggplot object (generated by `fgsea::plotEnrichment`).
#'
#' @importFrom fgsea plotEnrichment
#' @importFrom ggplot2 labs
#' @importFrom patchwork | +
#' @export
#' @examples
#' \dontrun{
#' gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' gsea_plot(gsea_res, "Group_Treat")
#' }
gsea_plot = function(gsea_res, set_names, show_table = FALSE){
    sample_sets = attr(gsea_res, "sampleSets")
    sample_ranks = attr(gsea_res, "sampleRanks")

    curve_data = get_curve_data(gsea_res, set_names)
    ticks_data = get_ticks_data(gsea_res, set_names)

    curve_plot = ggplot2::ggplot(curve_data, ggplot2::aes(.data[['rank']], .data[['ES']], color = .data[['set_name']])) +
        ggplot2::geom_line(size = 1) +
        ggplot2::geom_hline(yintercept = 0, linetype = "dashed") +
        ggplot2::labs(y = "Enrichment\nscore") +
        ggplot2::theme_bw() +
        ggplot2::theme(axis.text.x = ggplot2::element_blank(),
                       axis.ticks.x = ggplot2::element_blank(),
                       axis.title.x = ggplot2::element_blank(),
                       axis.title.y = ggplot2::element_text(vjust = -15))

    tick_plot = ggplot2::ggplot(ticks_data, ggplot2::aes(.data[['rank']], .data[['set_name']], fill = .data[['set_name']])) +
        ggplot2::geom_tile(width = 0.2, show.legend = FALSE) +
        ggplot2::labs(x = "Rank in ordered samples", y = NULL) +
        ggplot2::theme_bw() +
        ggplot2::theme(axis.text.x = ggplot2::element_blank(),
                       axis.ticks.x = ggplot2::element_blank())

    extra_data = gsea_res |>
        dplyr::select(dplyr::all_of(c('pathway','padj','NES'))) |>
        dplyr::filter(.data[['pathway']] %in% set_names) |>
        dplyr::mutate(
            padj = format(.data[['padj']], scientific = TRUE, digits = 2),
            NES = format(.data[['NES']], digits = 3)
        ) |>
        tibble::column_to_rownames('pathway')
    table_plot = ggpubr::ggtexttable(extra_data)

    combined_plot = curve_plot |>
        aplot::insert_bottom(tick_plot, height = 0.2)

    if (show_table) {
        (aplot::as.patchwork(combined_plot) | table_plot) +
            patchwork::plot_layout(widths = c(3,2))
    } else {
        combined_plot
    }

}

theme_gsea = function(){
    ggplot2::theme_bw() +
        ggplot2::theme(axis.text.x = ggplot2::element_blank(),
              axis.ticks.x = ggplot2::element_blank(),
              axis.title.x = ggplot2::element_blank())
}

ggGseaTable = function(gsea_res, set_names){
    ## 测试代码

    # 假设这是你的 GSEA 简表
    my_stats <- data.frame(
        Pathway = c("Cell Cycle", "Glycolysis", "Hypoxia"),
        NES = c(2.1, -1.8, 1.5),
        P_val = c("0.001", "0.02", "0.06")
    ) |>
        dplyr::mutate(row = dplyr::row_number()) |>
        dplyr::mutate_all(as.character) |>
        tidyr::pivot_longer(cols = -row, names_to = "col_name", values_to = "text")

    # 核心技巧：映射颜色
    p_table <- my_stats %>%
        dplyr::mutate(row_id = rev(dplyr::row_number()),
               sig_color = ifelse(as.numeric(.data[["NES"]]) > 0, "#E41A1C", "#377EB8")) %>%
        dplyr::mutate(dplyr::across(dplyr::everything(), as.character)) |>
        tidyr::pivot_longer(cols = c("Pathway", "NES", "P_val"), names_to = "col_name", values_to = "val") %>%
        dplyr::mutate(col_name = factor(.data[["col_name"]], levels = c("Pathway", "NES", "P_val"))) %>%
        ggplot2::ggplot(ggplot2::aes(x = .data[["col_name"]], y = .data[["row_id"]])) +
        ggplot2::geom_text(ggplot2::aes(label = .data[["val"]], color = .data[['sig_color']]), size = 4, fontface = "bold") +
        ggplot2::scale_color_identity() +
        ggplot2::annotate("text", x = 1:3, y = nrow(my_stats) + 0.8,
                 label = c("Pathway", "NES", "P-val"), fontface = "bold") +
        ggplot2::theme_void() +
        ggplot2::coord_cartesian(clip = "off")
}


get_curve_data = function(gsea_res, set_names){
  get_data(gsea_res, set_names, type = "curve")
}

get_ticks_data = function(gsea_res, set_names){
  get_data(gsea_res, set_names, type = "ticks")
}

get_data = function(gsea_res, set_names, type = c("curve", "ticks")){
    sample_sets = attr(gsea_res, "sampleSets")
    sample_ranks = attr(gsea_res, "sampleRanks")

    data_all = lapply(set_names, function(x) fgsea::plotEnrichmentData(sample_sets[[x]], sample_ranks))
    names(data_all) = set_names

    data = lapply(data_all, function(x) x[[type]]) |>
        dplyr::bind_rows(.id = "set_name")

    return(data)
}


#' Plot all GSEA enrichment score curves
#'
#' This function generates and arranges GSEA enrichment plots for all significant (or specified)
#' pathways from the GSEA results.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should contain the GSEA results
#'   and attributes "sampleSets" and "sampleRanks".
#' @param filter A logical value. If `TRUE` (default), filters the results to include only
#'   pathways with adjusted p-value < 0.05.
#' @param ... Additional arguments passed to `cowplot::plot_grid` (e.g., `ncol`, `labels`).
#'
#' @return A ggplot object (combined plot generated by `cowplot::plot_grid`).
#'
#' @importFrom dplyr filter
#' @importFrom cowplot plot_grid
#' @importFrom rlang .data
#' @export
#' @examples
#' \dontrun{
#' # gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' # gsea_plot_all(gsea_res)
#' }
gsea_plot_all = function(gsea_res, filter = TRUE, ...){
    if (filter){
        gsea_res = dplyr::filter(gsea_res, .data[['padj']] < 0.05)
    }
    sets = gsea_res$pathway
    if (length(sets) < 1){
        stop("At least one set needed.")
    }
    gsea_plot(gsea_res, sets)
}
