
#' Plot GSEA Enrichment Score
#'
#' This function plots the GSEA enrichment score curve for a specific sample set (pathway)
#' using the results from `run_microbiome_gsea`.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should be a
#'   data frame with "sampleSets" and "sampleRanks" attributes.
#' @param set_name A character string. The name of the set (pathway) to plot.
#'
#' @return A ggplot object (generated by `fgsea::plotEnrichment`).
#'
#' @importFrom fgsea plotEnrichment
#' @importFrom ggplot2 labs
#' @export
#' @examples
#' \dontrun{
#' gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' gsea_plot(gsea_res, "Group_Treat")
#' }
gsea_plot = function(gsea_res, set_name){
    sample_sets = attr(gsea_res, "sampleSets")
    sample_ranks = attr(gsea_res, "sampleRanks")

    p_val <- gsea_res$padj[gsea_res$pathway == set_name]
    p_val_fmt <- format(p_val, scientific = TRUE, digits = 3)
    NES <- format(gsea_res[["NES"]][gsea_res$pathway == set_name], digits = 3)

    lab = paste0(set_name, " (p.adj = ", p_val_fmt, ", NES = ", NES, ")")

    fgsea::plotEnrichment(sample_sets[[set_name]], sample_ranks) +
        ggplot2::labs(subtitle = lab)
}

#' Plot all GSEA enrichment score curves
#'
#' This function generates and arranges GSEA enrichment plots for all significant (or specified)
#' pathways from the GSEA results.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should contain the GSEA results
#'   and attributes "sampleSets" and "sampleRanks".
#' @param filter A logical value. If `TRUE` (default), filters the results to include only
#'   pathways with adjusted p-value < 0.05.
#' @param ... Additional arguments passed to `cowplot::plot_grid` (e.g., `ncol`, `labels`).
#'
#' @return A ggplot object (combined plot generated by `cowplot::plot_grid`).
#'
#' @importFrom dplyr filter
#' @importFrom cowplot plot_grid
#' @importFrom rlang .data
#' @export
#' @examples
#' \dontrun{
#' # gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' # gsea_plot_all(gsea_res)
#' }
gsea_plot_all = function(gsea_res, filter = TRUE, ...){
    if (filter){
        gsea_res = dplyr::filter(gsea_res, .data[['padj']] < 0.05)
    }
    sets = gsea_res$pathway
    if (length(sets) < 1){
        stop("At least one set needed.")
    }
    gglist = lapply(sets, gsea_plot, gsea_res = gsea_res)
    cowplot::plot_grid(plotlist = gglist, ...)
}
