
#' Plot GSEA Enrichment Score
#'
#' This function plots the GSEA enrichment score curve for a specific sample set (pathway)
#' using the results from `run_microbiome_gsea`.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should be a
#'   data frame with "sampleSets" and "sampleRanks" attributes.
#' @param set_names A character vector The name of the sets (pathway) to plot.
#' @param show_table A logical value. If `TRUE`, shows a table of p-values and NES alongside the plot.
#'
#' @return A ggplot object (generated by `fgsea::plotEnrichment`).
#'
#' @importFrom fgsea plotEnrichment
#' @importFrom ggplot2 labs
#' @import patchwork
#' @examples
#' \dontrun{
#'   gsea_res <- run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#'   gsea_plot(gsea_res, "Group_Treat")
#' }
#' @export
gsea_plot = function(gsea_res, set_names = NULL, show_table = FALSE){
    if (is.null(set_names)) {
      set_names <- if(is.factor(gsea_res$pathway)) levels(gsea_res$pathway) else gsea_res$pathway
    }

    curve_data = get_curve_data(gsea_res, set_names)
    ticks_data = get_ticks_data(gsea_res, set_names)

    curve_plot = ggplot2::ggplot(curve_data, ggplot2::aes(.data[['rank']], .data[['ES']], color = .data[['set_name']])) +
        ggplot2::geom_line(linewidth = 1) +
        ggplot2::geom_hline(yintercept = 0, linetype = "dashed") +
        ggplot2::labs(y = "Enrichment\nscore") +
        ggplot2::theme_bw() +
        ggplot2::theme(axis.text.x = ggplot2::element_blank(),
                       axis.ticks.x = ggplot2::element_blank(),
                       axis.title.x = ggplot2::element_blank(),
                       axis.title.y = ggplot2::element_text(vjust = -15))

    tick_plot = ggplot2::ggplot(ticks_data, ggplot2::aes(.data[['rank']], .data[['set_name']], fill = .data[['set_name']])) +
        ggplot2::geom_tile(width = 0.2, show.legend = FALSE) +
        ggplot2::labs(x = "Rank in ordered samples", y = NULL) +
        ggplot2::theme_bw() +
        ggplot2::theme(axis.text.x = ggplot2::element_blank(),
                       axis.ticks.x = ggplot2::element_blank()) +
      ggplot2::scale_y_discrete(limits = rev(set_names))

    extra_data = gsea_res |>
        dplyr::select(dplyr::all_of(c('pathway','padj','NES'))) |>
        dplyr::filter(.data[['pathway']] %in% set_names) |>
        dplyr::mutate(
            padj = format(.data[['padj']], scientific = TRUE, digits = 2),
            NES = format(.data[['NES']], digits = 3)
        ) |>
        tibble::column_to_rownames('pathway')
    table_plot = ggpubr::ggtexttable(extra_data)

    combined_plot = curve_plot |>
        aplot::insert_bottom(tick_plot, height = 0.2)

    if (show_table) {
        (aplot::as.patchwork(combined_plot) | table_plot) +
            patchwork::plot_layout(widths = c(3,2))
    } else {
        combined_plot
    }

}

#' Plot GSEA Enrichment Score Barcodes for Multiple Sets
#'
#' This function generates barcode plots for multiple GSEA pathways, displaying the enrichment score ticks
#' along with pathway names and statistics (size, NES, adjusted p-value).
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should be a
#'  data frame with "sampleSets" and "sampleRanks" attributes.
#' @param set_names A character vector The names of the sets (pathways) to plot.
#'
#' @return A ggplot object (combined barcode plots for the specified pathways).
#'
#' @export
#' @examples
#'  \dontrun{
#'  gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#'  gsea_plot_barcode(gsea_res)
#'}
gsea_plot_barcode = function(
    gsea_res,
    set_names = gsea_res[['pathway']]){

  ticks_data = get_ticks_data(gsea_res, set_names)

  plots = lapply(set_names, function(x){
    current_stat = gsea_res[gsea_res$pathway == x, ] |>
      dplyr::mutate(
        padj = format(.data[['padj']], scientific = TRUE, digits = 2),
        NES = format(.data[['NES']], digits = 3)
      )
    current_tick <- ticks_data[ticks_data$set_name == x, ]
    p_name = ggplot2::ggplot() +
      ggplot2::annotate("text", x = 0, y = 0, label = x, fontface = "bold") +
      ggplot2::theme_void()
    p_barcode = tick_plot(current_tick) +
      ggplot2::theme(
        axis.title.y = ggplot2::element_blank(),
      )
    p_table = do.call(header_plot, list(x = unlist(current_stat[, c("size","NES","padj")]))) |>
      Reduce(f = aplot::insert_right) |>
      aplot::as.patchwork()

    p_barcode |>
      aplot::insert_left(p_name) |>
      aplot::insert_right(p_table) |>
      aplot::as.patchwork()
  })

  plot_rows = patchwork::wrap_plots(plots, ncol = 1)

  return(plot_rows)
}

header_plot = function(x, widths = nchar(x)){
  if (length(x) > 0) {
    plots = lapply(x, function(t){
      ggplot2::ggplot() +
        ggplot2::annotate("text", x = 1, y = 0, label = t, fontface = "bold") +
        ggplot2::theme_void()
    })
  }
  return(plots)
}

table_plot = function(stat_data, columns = c("size","NES","padj")){
  stat_data = stat_data |>
    dplyr::select(dplyr::all_of(columns)) |>
    dplyr::mutate(
      padj = format(.data[['padj']], scientific = TRUE, digits = 2),
      NES = format(.data[['NES']], digits = 3)
    ) |>
    dplyr::mutate_all(as.character) |>
    tidyr::pivot_longer(names_to = "col_name", values_to = "text", cols = dplyr::everything())

  ggplot2::ggplot(stat_data, ggplot2::aes(x = .data[['col_name']], y = 0)) +
    ggplot2::geom_text(ggplot2::aes(label = .data[['text']]), size = 4, fontface = "bold") +
    ggplot2::theme_void() +
    ggplot2::coord_cartesian(clip = "off")
}

tick_plot = function(tick_data){
  ggplot2::ggplot(tick_data, ggplot2::aes(.data[['rank']], .data[['stat']]/2)) +
    ggplot2::geom_tile(ggplot2::aes(height = .data[["stat"]]), width = 0.2, show.legend = FALSE) +
    ggplot2::geom_hline(yintercept = 0, color = "grey", linewidth = 0.2) +
    ggplot2::theme_void()
}

get_curve_data = function(gsea_res, set_names){
  get_data(gsea_res, set_names, type = "curve")
}

get_ticks_data = function(gsea_res, set_names){
  get_data(gsea_res, set_names, type = "ticks")
}

get_data = function(gsea_res, set_names, type = c("curve", "ticks")){
    sample_sets = attr(gsea_res, "sampleSets")
    sample_ranks = attr(gsea_res, "sampleRanks")

    data_all = lapply(set_names, function(x) fgsea::plotEnrichmentData(sample_sets[[x]], sample_ranks))
    names(data_all) = set_names

    data = lapply(data_all, function(x) x[[type]]) |>
      dplyr::bind_rows(.id = "set_name")

    data |> dplyr::mutate(set_name = factor(.data[['set_name']], levels = set_names))

}


#' Plot all GSEA enrichment score curves
#'
#' This function generates and arranges GSEA enrichment plots for all significant (or specified)
#' pathways from the GSEA results.
#'
#' @param gsea_res A result object from `run_microbiome_gsea`. It should contain the GSEA results
#'   and attributes "sampleSets" and "sampleRanks".
#' @param filter A logical value. If `TRUE` (default), filters the results to include only
#'   pathways with adjusted p-value < 0.05.
#' @param ... Additional arguments passed to `cowplot::plot_grid` (e.g., `ncol`, `labels`).
#'
#' @return A ggplot object (combined plot generated by `cowplot::plot_grid`).
#'
#' @importFrom dplyr filter
#' @importFrom cowplot plot_grid
#' @importFrom rlang .data
#' @export
#' @examples
#' \dontrun{
#' # gsea_res = run_microbiome_gsea(ps_test_data, "Genus1", "Genus", c("Group","Source"))
#' # gsea_plot_all(gsea_res)
#' }
gsea_plot_all = function(gsea_res, filter = TRUE, ...){
    if (filter){
        gsea_res = dplyr::filter(gsea_res, .data[['padj']] < 0.05)
    }
    sets = gsea_res$pathway
    if (length(sets) < 1){
        stop("At least one set needed.")
    }
    gsea_plot(gsea_res, sets)
}
